name: zipDMG

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: zipDMG
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Mount DMG and zip it
        run:  chmod +x mount.sh && bash mount.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zipDMG Output
          path: |
              /tmp/output.tar.gz
